spring.application.name=tradelogs


spring.application.name=Land Trade

# 공통 설정
server.port=8080
## local profile을 기본으로 활성화
spring.profiles.active=local

# 타임아웃/재시도 설정
connect-timeout-mills=3000
response-timeout-mills=5000
retry-max-attemps=3
retry-backoff-mills=500

# Open API 서버 설정 (아파트 실거래가)
com.jake.tradelogs.config.apt.base-url=https://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev
com.jake.tradelogs.config.apt.service-path=/getRTMSDataSvcAptTradeDev
com.jake.tradelogs.config.apt.service-key=
com.jake.tradelogs.config.apt.default-page-size=50
com.jake.tradelogs.config.apt.connect-timeout-mills=${connect-timeout-mills}
com.jake.tradelogs.config.apt.response-timeout-mills=${response-timeout-mills}
com.jake.tradelogs.config.apt.retry-max-attemps=${retry-max-attemps}
com.jake.tradelogs.config.apt.retry-backoff-mills=${retry-backoff-mills}

# Open API 서버 설정 (법정동코드)
com.jake.tradelogs.config.lawd.base-url=https://apis.data.go.kr/1741000/StanReginCd
com.jake.tradelogs.config.lawd.service-path=/getStanReginCdList
com.jake.tradelogs.config.lawd.service-key=
com.jake.tradelogs.config.lawd.default-page-size=10
com.jake.tradelogs.config.lawd.connect-timeout-mills=${connect-timeout-mills}
com.jake.tradelogs.config.lawd.response-timeout-mills=${response-timeout-mills}
com.jake.tradelogs.config.lawd.retry-max-attemps=${retry-max-attemps}
com.jake.tradelogs.config.lawd.retry-backoff-mills=${retry-backoff-mills}

logging.level.com.jake.tradelogs=DEBUG

# MariaDB 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/tradelogs
spring.datasource.username=root
spring.datasource.password=1234

# MyBatis 설정
## mapper xml 파일 경로
mybatis.mapper-locations=classpath:mapper/*.xml

mybatis.type-aliases-package=com.jake.tradelogs
## DB의 컬럼명에 언더스코어를 자바 객체의 카멜표기(camelCase)로 자동 변환해주는 설정
## DB 컬럼명이 user_id라면, 자바 객체 필드명을 userId로 자동 매핑된다
mybatis.configuration.map-underscore-to-camel-case=true
## SQL 쿼리 결과를 console에 출력한다.
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# DEBUG 설정
logging.level.com.jake.tradelogs.mapper=DEBUG
logging.level.com.jake.tradelogs.service=DEBUG